// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmy6LdhsuiAZxTvI3ZseORemKJHUAjgSs',
    appId: '1:662051055341:web:9afb59c15061ce5b89cee4',
    messagingSenderId: '662051055341',
    projectId: 'flutterauth-e6495',
    authDomain: 'flutterauth-e6495.firebaseapp.com',
    storageBucket: 'flutterauth-e6495.appspot.com',
    measurementId: 'G-Q3H2LDS63N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqqplpBOXCTbToDmIVLv-JTXqhgFqkFrs',
    appId: '1:662051055341:android:1de84204aac41e0d89cee4',
    messagingSenderId: '662051055341',
    projectId: 'flutterauth-e6495',
    storageBucket: 'flutterauth-e6495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt0vGWDwlCs7TXBAvYUp19fiPnBViwyr8',
    appId: '1:662051055341:ios:639696653ab79ed989cee4',
    messagingSenderId: '662051055341',
    projectId: 'flutterauth-e6495',
    storageBucket: 'flutterauth-e6495.appspot.com',
    iosBundleId: 'com.example.seLab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt0vGWDwlCs7TXBAvYUp19fiPnBViwyr8',
    appId: '1:662051055341:ios:8a99426ca3714de389cee4',
    messagingSenderId: '662051055341',
    projectId: 'flutterauth-e6495',
    storageBucket: 'flutterauth-e6495.appspot.com',
    iosBundleId: 'com.example.seLab.RunnerTests',
  );
}
